baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tomek Garbus'
theme = 'papermod'
toc = true
sectionPagesMenu = "main"

[params]
[params.homeInfoParams]
Title = 'Hi!'
Content = 'Tekst dolny'